name: run-deploy

on:
  push:
    branches: [main]
jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: ./deploy.sh
